export { default as Archive } from './Archive';
export { default as Backward } from './Backward';
export { default as Bell } from './Bell';
export { default as BirthdayCake } from './BirthdayCake';
export { default as Book } from './Book';
export { default as Book1 } from './Book1';
export { default as Bookmark } from './Bookmark';
export { default as BoxCheck } from './BoxCheck';
export { default as BoxDuplicate } from './BoxDuplicate';
export { default as BoxS } from './BoxS';
export { default as Briefcase1 } from './Briefcase1';
export { default as Briefcase2 } from './Briefcase2';
export { default as Browser } from './Browser';
export { default as Bug } from './Bug';
export { default as Building } from './Building';
export { default as Bus } from './Bus';
export { default as Cachet } from './Cachet';
export { default as Calculator } from './Calculator';
export { default as CalendarBoxes } from './CalendarBoxes';
export { default as CalendarChecked } from './CalendarChecked';
export { default as CalendarClose } from './CalendarClose';
export { default as CalendarEdit } from './CalendarEdit';
export { default as CalendarEmpty } from './CalendarEmpty';
export { default as CalendarHint } from './CalendarHint';
export { default as CalendarMinus } from './CalendarMinus';
export { default as CalendarPlus } from './CalendarPlus';
export { default as Camera } from './Camera';
export { default as Car } from './Car';
export { default as Cash } from './Cash';
export { default as ChartBarchart } from './ChartBarchart';
export { default as ChartLinechart } from './ChartLinechart';
export { default as ChartPiechart } from './ChartPiechart';
export { default as ChartTrend } from './ChartTrend';
export { default as Check } from './Check';
export { default as ChecklistChecked } from './ChecklistChecked';
export { default as ChecklistUnchecked } from './ChecklistUnchecked';
export { default as CircleCheck } from './CircleCheck';
export { default as CircleInfo } from './CircleInfo';
export { default as CircleQuestion } from './CircleQuestion';
export { default as Clock } from './Clock';
export { default as Close } from './Close';
export { default as Cloud } from './Cloud';
export { default as CloudDownload } from './CloudDownload';
export { default as CloudUpload } from './CloudUpload';
export { default as Code } from './Code';
export { default as Coffee } from './Coffee';
export { default as CreditCard } from './CreditCard';
export { default as Diamond } from './Diamond';
export { default as DoorClosed } from './DoorClosed';
export { default as DoorOpened } from './DoorOpened';
export { default as Edit } from './Edit';
export { default as Export } from './Export';
export { default as Eye } from './Eye';
export { default as EyeBlind } from './EyeBlind';
export { default as EyeO } from './EyeO';
export { default as FaceId } from './FaceId';
export { default as FileCode } from './FileCode';
export { default as FileContent } from './FileContent';
export {
  default as FileContentDuplicate,
} from './FileContentDuplicate';
export { default as FileDuplicate } from './FileDuplicate';
export { default as FileEmpty } from './FileEmpty';
export { default as FileExcel } from './FileExcel';
export { default as FileJpg } from './FileJpg';
export { default as FileKeynote } from './FileKeynote';
export { default as FileNumbers } from './FileNumbers';
export { default as FilePages } from './FilePages';
export { default as FilePaper } from './FilePaper';
export { default as FilePdf } from './FilePdf';
export { default as FilePlus } from './FilePlus';
export { default as FilePng } from './FilePng';
export { default as FilePowerpoint } from './FilePowerpoint';
export { default as FileS } from './FileS';
export { default as FileSketch } from './FileSketch';
export { default as FileUnknow } from './FileUnknow';
export { default as FileWord } from './FileWord';
export { default as Filter } from './Filter';
export { default as FinderClosed } from './FinderClosed';
export { default as FinderOpened } from './FinderOpened';
export { default as FinderPlus } from './FinderPlus';
export { default as FirstAid } from './FirstAid';
export { default as Flag } from './Flag';
export { default as Gear } from './Gear';
export { default as Glasses } from './Glasses';
export { default as HardDriveDownload } from './HardDriveDownload';
export { default as Heart } from './Heart';
export { default as House } from './House';
export { default as Human } from './Human';
export { default as IdCard } from './IdCard';
export { default as Key } from './Key';
export { default as Lamp } from './Lamp';
export { default as Link } from './Link';
export { default as Magnifier } from './Magnifier';
export { default as Mail } from './Mail';
export { default as MailRead } from './MailRead';
export { default as MessageRounded } from './MessageRounded';
export {
  default as MessageRoundedClose,
} from './MessageRoundedClose';
export {
  default as MessageRoundedContent,
} from './MessageRoundedContent';
export {
  default as MessageRoundedDialogue,
} from './MessageRoundedDialogue';
export { default as MessageRoundedHint } from './MessageRoundedHint';
export { default as MessageRoundedMore } from './MessageRoundedMore';
export { default as MessageRoundedPlus } from './MessageRoundedPlus';
export {
  default as MessageRoundedSmile,
} from './MessageRoundedSmile';
export { default as MessageSquare } from './MessageSquare';
export { default as MessageSquareClose } from './MessageSquareClose';
export {
  default as MessageSquareContent,
} from './MessageSquareContent';
export { default as MessageSquareHint } from './MessageSquareHint';
export { default as MessageSquareMore } from './MessageSquareMore';
export { default as MessageSquarePlus } from './MessageSquarePlus';
export { default as MessageSquareSmile } from './MessageSquareSmile';
export { default as Moon } from './Moon';
export { default as MoreOption } from './MoreOption';
export { default as Music } from './Music';
export { default as Mute } from './Mute';
export { default as News } from './News';
export { default as Notification } from './Notification';
export { default as Pen } from './Pen';
export { default as Pin } from './Pin';
export { default as Rocket } from './Rocket';
export { default as Scale } from './Scale';
export { default as Setting } from './Setting';
export { default as Share } from './Share';
export { default as Sofa } from './Sofa';
export { default as Spanner } from './Spanner';
export { default as StampChecked } from './StampChecked';
export { default as Star } from './Star';
export { default as Tag } from './Tag';
export { default as Trash } from './Trash';
export { default as Umbrella } from './Umbrella';
export { default as WaterDrop } from './WaterDrop';
export { default as ZoomIn } from './ZoomIn';
export { default as ZoomOut } from './ZoomOut';
