image: node:6.9.4

pipelines:
  branches:
    master:
      - step:
          script:
            - npm install -g surge
            - npm install
            - npm run build-storybook
            - surge storybook-static illegal-number.surge.sh
