import React from 'react';

export const EmptyIconSvg = () => (
  <svg
    width="118px"
    height="90px"
    viewBox="0 0 118 90"
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g
      id="table"
      stroke="none"
      stroke-width="1"
      fill="none"
      fill-rule="evenodd"
    >
      <g id="Table" transform="translate(-569.000000, -2752.000000)">
        <g id="Group" transform="translate(569.000000, 2752.000000)">
          <g
            id="Group-15-Copy"
            transform="translate(110.000000, 20.000000)"
            fill="#DEDEE2"
          >
            <g id="Group-4">
              <rect
                id="Rectangle"
                x="3.2"
                y="0"
                width="1.6"
                height="8"
                rx="0.8"
              />
              <rect
                id="Rectangle-Copy-3"
                x="0"
                y="3.2"
                width="8"
                height="1.6"
                rx="0.8"
              />
            </g>
          </g>
          <g
            id="Group-5-Copy"
            transform="translate(0.000000, 9.000000)"
            fill="#DEDEE2"
          >
            <rect
              id="Rectangle-Copy"
              x="4"
              y="0"
              width="3"
              height="11"
              rx="1.5"
            />
            <rect
              id="Rectangle-Copy-6"
              x="0"
              y="4"
              width="11"
              height="3"
              rx="1.5"
            />
          </g>
          <g
            id="Group-14-Copy"
            transform="translate(102.000000, 31.000000)"
            fill="#DEDEE2"
          >
            <rect
              id="Rectangle"
              x="3"
              y="0"
              width="2"
              height="8"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-3"
              x="0"
              y="3"
              width="8"
              height="2"
              rx="1"
            />
          </g>
          <ellipse
            id="Oval"
            fill="#F0F0F2"
            cx="64.5"
            cy="82"
            rx="42.5"
            ry="8"
          />
          <g
            id="Group-4-Copy"
            transform="translate(20.000000, 0.000000)"
          >
            <rect
              id="Rectangle"
              stroke="#F0F0F2"
              stroke-width="2"
              fill="#F9F9FA"
              x="1"
              y="1"
              width="86"
              height="20"
              rx="8"
            />
            <rect
              id="Rectangle"
              fill="#DEDEE2"
              x="6"
              y="9"
              width="10"
              height="4"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-2"
              fill="#DEDEE2"
              x="22"
              y="9"
              width="32"
              height="4"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-15"
              fill="#DEDEE2"
              x="59"
              y="9"
              width="23"
              height="4"
              rx="2"
            />
          </g>
          <g
            id="Group-4-Copy-3"
            transform="translate(20.000000, 47.000000)"
          >
            <g id="Group-13">
              <rect
                id="Rectangle"
                stroke="#F0F0F2"
                stroke-width="2"
                fill="#F9F9FA"
                x="1"
                y="1"
                width="86"
                height="20"
                rx="8"
              />
              <rect
                id="Rectangle"
                fill="#DEDEE2"
                x="5.72357724"
                y="9"
                width="10.0162602"
                height="4"
                rx="2"
              />
              <rect
                id="Rectangle-Copy-2"
                fill="#DEDEE2"
                x="21.4634146"
                y="9"
                width="32.195122"
                height="4"
                rx="2"
              />
              <rect
                id="Rectangle-Copy-15"
                fill="#DEDEE2"
                x="59.3821138"
                y="9"
                width="22.8943089"
                height="4"
                rx="2"
              />
            </g>
          </g>
          <g
            id="Group-4-Copy-2"
            transform="translate(11.000000, 18.000000)"
          >
            <rect
              id="Rectangle"
              stroke="#F0F0F2"
              stroke-width="2"
              fill="#FFFFFF"
              x="1"
              y="1"
              width="86"
              height="20"
              rx="8"
            />
            <rect
              id="Rectangle"
              fill="#DEDEE2"
              x="6"
              y="9"
              width="10"
              height="4"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-2"
              fill="#DEDEE2"
              x="22"
              y="9"
              width="32"
              height="4"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-15"
              fill="#DEDEE2"
              x="59"
              y="9"
              width="23"
              height="4"
              rx="2"
            />
          </g>
        </g>
      </g>
    </g>
  </svg>
);
