// flow-typed signature: 5bca927489aafbeff5e19528ac6e7d93
// flow-typed version: <<STUB>>/babel-plugin-react-docgen_v1.9.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-docgen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-docgen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-docgen/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/lib/isReactComponentClass' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/lib/isStatelessComponent' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case1/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case1/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case2/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case2/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case3/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case3/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case4/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case4/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case5/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case5/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case6/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case6/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case7/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case7/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case8/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case8/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case9/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/case9/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/createReactClass/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/createReactClass/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/example-module-exports/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/example-module-exports/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/example/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/example/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/flowType/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/flowType/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/functionDeclaration/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/functionDeclaration/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/hoc-multiple/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/hoc-multiple/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/hoc/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/hoc/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/reactCreateClass/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/reactCreateClass/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/reactCreateElement/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/fixtures/reactCreateElement/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-docgen/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-docgen/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/lib/index'>;
}
declare module 'babel-plugin-react-docgen/lib/isReactComponentClass.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/lib/isReactComponentClass'>;
}
declare module 'babel-plugin-react-docgen/lib/isStatelessComponent.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/lib/isStatelessComponent'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case1/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case1/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case1/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case1/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case2/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case2/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case2/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case2/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case3/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case3/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case3/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case3/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case4/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case4/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case4/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case4/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case5/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case5/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case5/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case5/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case6/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case6/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case6/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case6/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case7/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case7/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case7/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case7/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case8/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case8/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case8/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case8/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case9/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case9/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/case9/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/case9/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/createReactClass/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/createReactClass/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/createReactClass/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/createReactClass/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/example-module-exports/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/example-module-exports/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/example-module-exports/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/example-module-exports/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/example/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/example/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/example/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/example/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/flowType/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/flowType/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/flowType/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/flowType/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/functionDeclaration/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/functionDeclaration/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/functionDeclaration/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/functionDeclaration/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/hoc-multiple/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/hoc-multiple/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/hoc-multiple/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/hoc-multiple/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/hoc/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/hoc/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/hoc/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/hoc/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/reactCreateClass/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/reactCreateClass/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/reactCreateClass/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/reactCreateClass/expected'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/reactCreateElement/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/reactCreateElement/actual'>;
}
declare module 'babel-plugin-react-docgen/test/fixtures/reactCreateElement/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/fixtures/reactCreateElement/expected'>;
}
declare module 'babel-plugin-react-docgen/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-docgen/test/index'>;
}
