// flow-typed signature: dd34c23273b83fa8329596ce89766a45
// flow-typed version: <<STUB>>/babel-plugin-root-import_v5.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-root-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-root-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-root-import/build/helper' {
  declare module.exports: any;
}

declare module 'babel-plugin-root-import/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-root-import/build/helper.js' {
  declare module.exports: $Exports<'babel-plugin-root-import/build/helper'>;
}
declare module 'babel-plugin-root-import/build/index.js' {
  declare module.exports: $Exports<'babel-plugin-root-import/build/index'>;
}
declare module 'babel-plugin-root-import/index' {
  declare module.exports: $Exports<'babel-plugin-root-import'>;
}
declare module 'babel-plugin-root-import/index.js' {
  declare module.exports: $Exports<'babel-plugin-root-import'>;
}
