// flow-typed signature: 37b2737b722f2338612dcc22f2761d8d
// flow-typed version: <<STUB>>/markdown-loader-jest_v0.1.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-loader-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-loader-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'markdown-loader-jest/index' {
  declare module.exports: $Exports<'markdown-loader-jest'>;
}
declare module 'markdown-loader-jest/index.js' {
  declare module.exports: $Exports<'markdown-loader-jest'>;
}
