// flow-typed signature: 8e150cc24472f0c7ec1cb96b3b8bc73c
// flow-typed version: <<STUB>>/rollup-plugin-visualizer_v0.6.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-visualizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-visualizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-visualizer/lib/pluginmain' {
  declare module.exports: any;
}

declare module 'rollup-plugin-visualizer/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-visualizer/lib/pluginmain.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/lib/pluginmain'>;
}
declare module 'rollup-plugin-visualizer/plugin.js' {
  declare module.exports: $Exports<'rollup-plugin-visualizer/plugin'>;
}
