// flow-typed signature: e92f2f77265e36a1ea912b4c095fe2f1
// flow-typed version: <<STUB>>/rollup-plugin-auto-external_v^1.2.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-auto-external'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-auto-external' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-auto-external/index' {
  declare module.exports: $Exports<'rollup-plugin-auto-external'>;
}
declare module 'rollup-plugin-auto-external/index.js' {
  declare module.exports: $Exports<'rollup-plugin-auto-external'>;
}
