// flow-typed signature: 980f35d66e45ea61226eb9ee7ce65e72
// flow-typed version: <<STUB>>/rollup-plugin-postcss_v1.5.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-postcss/dist/rollup-plugin-postcss.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-postcss/dist/rollup-plugin-postcss.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-postcss/dist/rollup-plugin-postcss.cjs'>;
}
