// flow-typed signature: c2c6de1c32091875424f2c5e3878fce6
// flow-typed version: <<STUB>>/styled-theme_v^0.3.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-theme/composer' {
  declare module.exports: any;
}

declare module 'styled-theme/dist/composer' {
  declare module.exports: any;
}

declare module 'styled-theme/dist/index' {
  declare module.exports: any;
}

declare module 'styled-theme/dist/theme' {
  declare module.exports: any;
}

declare module 'styled-theme/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-theme/composer.js' {
  declare module.exports: $Exports<'styled-theme/composer'>;
}
declare module 'styled-theme/dist/composer.js' {
  declare module.exports: $Exports<'styled-theme/dist/composer'>;
}
declare module 'styled-theme/dist/index.js' {
  declare module.exports: $Exports<'styled-theme/dist/index'>;
}
declare module 'styled-theme/dist/theme.js' {
  declare module.exports: $Exports<'styled-theme/dist/theme'>;
}
declare module 'styled-theme/dist/types.js' {
  declare module.exports: $Exports<'styled-theme/dist/types'>;
}
declare module 'styled-theme/index' {
  declare module.exports: $Exports<'styled-theme'>;
}
declare module 'styled-theme/index.js' {
  declare module.exports: $Exports<'styled-theme'>;
}
