version: 2

# Ref vars
references: 
  container_config: &container_config
    docker:
      - image: circleci/node:8.11.3@sha256:38bca14e7fa26f30d477991460c118c320dd18899030b8220fe709c46a3f98e7
  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo
jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-

      - run:
          name: Install Dependencies
          command: |
            sudo npm install -g yarn
            sudo yarn config set cache-folder .yarn-cache
            sudo yarn install --pure-lockfile
      - run: yarn cache dir
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - .yarn-cache
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  lint_check: 
    <<: *container_config
    steps:
      - *attach_workspace 
      - run: yarn run lint
  
  test: 
    <<: *container_config
    steps:
      - *attach_workspace
      - run: 
          name: Test storyshots
          command: yarn run test:web
      

workflows:
  version: 2

  test_and_lint:
    jobs:
      - checkout_code
      - lint_check:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
