# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.19

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    # working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-cache-v2-{{ checksum "yarn.lock" }}
            - yarn-cache-v2
      - restore_cache:
          keys:
            - dependency-cache-v2-{{ checksum "yarn.lock" }}
            - dependency-cache-v2
      - run:
          name: Install Dependencies
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | sudo bash
            sudo yarn config set cache-folder .yarn-cache-v2
            sudo yarn install --frozen-lockfile
      - run: yarn cache dir
      - save_cache:
          key: yarn-cache-v2-{{ checksum "yarn.lock" }}
          paths:
            - .yarn-cache-v2
      - save_cache:
          key: dependency-cache-v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint check
          command: yarn run lint
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Test
          command: yarn run test
