// flow-typed signature: 674149a7d4d1b97b8fa82f54f850d7c2
// flow-typed version: <<STUB>>/@gssfed/eslint-config_v0.0.3/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@gssfed/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@gssfed/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@gssfed/eslint-config/base' {
  declare module.exports: any;
}

declare module '@gssfed/eslint-config/legacy' {
  declare module.exports: any;
}

declare module '@gssfed/eslint-config/rules/react-a11y' {
  declare module.exports: any;
}

declare module '@gssfed/eslint-config/rules/react' {
  declare module.exports: any;
}

declare module '@gssfed/eslint-config/test/requires' {
  declare module.exports: any;
}

declare module '@gssfed/eslint-config/test/test-base' {
  declare module.exports: any;
}

declare module '@gssfed/eslint-config/test/test-react-order' {
  declare module.exports: any;
}

declare module '@gssfed/eslint-config/whitespace' {
  declare module.exports: any;
}

// Filename aliases
declare module '@gssfed/eslint-config/base.js' {
  declare module.exports: $Exports<'@gssfed/eslint-config/base'>;
}
declare module '@gssfed/eslint-config/index' {
  declare module.exports: $Exports<'@gssfed/eslint-config'>;
}
declare module '@gssfed/eslint-config/index.js' {
  declare module.exports: $Exports<'@gssfed/eslint-config'>;
}
declare module '@gssfed/eslint-config/legacy.js' {
  declare module.exports: $Exports<'@gssfed/eslint-config/legacy'>;
}
declare module '@gssfed/eslint-config/rules/react-a11y.js' {
  declare module.exports: $Exports<'@gssfed/eslint-config/rules/react-a11y'>;
}
declare module '@gssfed/eslint-config/rules/react.js' {
  declare module.exports: $Exports<'@gssfed/eslint-config/rules/react'>;
}
declare module '@gssfed/eslint-config/test/requires.js' {
  declare module.exports: $Exports<'@gssfed/eslint-config/test/requires'>;
}
declare module '@gssfed/eslint-config/test/test-base.js' {
  declare module.exports: $Exports<'@gssfed/eslint-config/test/test-base'>;
}
declare module '@gssfed/eslint-config/test/test-react-order.js' {
  declare module.exports: $Exports<'@gssfed/eslint-config/test/test-react-order'>;
}
declare module '@gssfed/eslint-config/whitespace.js' {
  declare module.exports: $Exports<'@gssfed/eslint-config/whitespace'>;
}
