// flow-typed signature: cc097d0605417c14157e97abd48ba037
// flow-typed version: <<STUB>>/@storybook/addon-notes_v^3.3.14/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-notes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-notes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-notes/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/dist/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/src/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/src/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/src/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-notes/src/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-notes/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/index'>;
}
declare module '@storybook/addon-notes/dist/react.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/react'>;
}
declare module '@storybook/addon-notes/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/dist/register'>;
}
declare module '@storybook/addon-notes/register.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/register'>;
}
declare module '@storybook/addon-notes/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/src/index'>;
}
declare module '@storybook/addon-notes/src/react.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/src/react'>;
}
declare module '@storybook/addon-notes/src/register.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/src/register'>;
}
declare module '@storybook/addon-notes/src/stories/index.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/src/stories/index'>;
}
declare module '@storybook/addon-notes/src/tests/index.js' {
  declare module.exports: $Exports<'@storybook/addon-notes/src/tests/index'>;
}
